import { mortgage, payoff } from "./algorithms.ts";

export type CalculatorValues = Record<string, number>;
export type CalculatorField = { key: string; label: string; defaultValue: number; min?: number; max?: number; step?: number; suffix?: string };
export type ResultRow = { key: string; label: string; value: string };
export type CalculatorDefinition = { fields: CalculatorField[]; calculate: (values: CalculatorValues) => ResultRow[] };

const number = (value: number) => new Intl.NumberFormat(undefined, { maximumFractionDigits: 2 }).format(Number.isFinite(value) ? value : 0);
const money = (value: number) => number(value);
const percent = (value: number) => `${number(value)}%`;
const row = (key: string, label: string, value: string | number): ResultRow => ({ key, label, value: String(value) });
const field = (key: string, label: string, defaultValue: number, extras: Partial<CalculatorField> = {}): CalculatorField => ({ key, label, defaultValue, ...extras });

export const calculators: Record<string, CalculatorDefinition> = {
  mortgage: { fields: [field("homePrice", "Home price", 500000), field("downPayment", "Down payment", 100000), field("annualRate", "Interest rate %", 4, { step: .01 }), field("termYears", "Term years", 30)], calculate: v => { const principal = Math.max(0, v.homePrice - v.downPayment); const x = mortgage(principal, v.annualRate, v.termYears); return [row("loanAmount", "Loan amount", money(principal)), row("monthlyPayment", "Monthly payment", money(x.payment)), row("totalInterest", "Total interest", money(x.interest)), row("totalRepayment", "Total repayment", money(x.total))]; } },
  leverage: { fields: [field("propertyValue", "Property value", 500000), field("downPercent", "Down payment %", 20), field("dropPercent", "Price drop %", 15), field("annualRate", "Interest rate %", 4)], calculate: v => { const equity = v.propertyValue * v.downPercent / 100, loan = v.propertyValue - equity; return [row("loan", "Loan", money(loan)), row("leverage", "Leverage", `${equity ? (v.propertyValue / equity).toFixed(2) : 0}×`), row("equityAfterDrop", "Equity after drop", money(v.propertyValue * (1 - v.dropPercent / 100) - loan))]; } },
  prepayment: { fields: [field("balance", "Loan balance", 400000), field("annualRate", "Interest rate %", 4), field("termYears", "Term years", 25), field("extraMonthly", "Extra / month", 500)], calculate: v => { const base = payoff(v.balance, v.annualRate, v.termYears), fast = payoff(v.balance, v.annualRate, v.termYears, v.extraMonthly); return [row("monthsSaved", "Months saved", number(base.months - fast.months)), row("interestSaved", "Interest saved", money(base.interest - fast.interest)), row("newPayoff", "New payoff", `${fast.months} months`)]; } },
  rentbuy: { fields: [field("homePrice", "Home price", 500000), field("monthlyRent", "Monthly rent", 2200), field("years", "Years", 10), field("homeGrowth", "Home growth %", 3)], calculate: v => { const rent = v.monthlyRent * 12 * v.years, owned = v.homePrice * .2 + v.homePrice * .8 * .04 * v.years - v.homePrice * ((1 + v.homeGrowth / 100) ** v.years - 1); return [row("rentPaid", "Rent paid", money(rent)), row("estimatedBuyCost", "Estimated buy cost", money(owned)), row("lowerEstimate", "Lower estimate", rent < owned ? "Rent" : "Buy")]; } },
  rental: { fields: [field("propertyPrice", "Property price", 500000), field("monthlyRent", "Monthly rent", 3000), field("annualExpenses", "Annual expenses", 8000), field("downPercent", "Down payment %", 20)], calculate: v => { const income = v.monthlyRent * 12 - v.annualExpenses; return [row("annualCashFlow", "Annual cash flow", money(income)), row("grossYield", "Gross yield", percent(v.monthlyRent * 12 / v.propertyPrice * 100)), row("capRate", "Cap rate", percent(income / v.propertyPrice * 100))]; } },
  compound: { fields: [field("starting", "Starting amount", 10000), field("monthly", "Monthly contribution", 500), field("annualReturn", "Annual return %", 7), field("years", "Years", 20)], calculate: v => { const r = v.annualReturn / 1200, n = v.years * 12, future = r ? v.starting * (1 + r) ** n + v.monthly * ((1 + r) ** n - 1) / r : v.starting + v.monthly * n, contributed = v.starting + v.monthly * n; return [row("futureValue", "Future value", money(future)), row("contributed", "Contributed", money(contributed)), row("growth", "Growth", money(future - contributed))]; } },
  fire: { fields: [field("annualSpending", "Annual spending", 60000), field("investments", "Current investments", 150000), field("monthlySavings", "Monthly savings", 2500), field("withdrawalRate", "Withdrawal rate %", 4)], calculate: v => { const target = v.annualSpending / (v.withdrawalRate / 100 || .04), r = .05 / 12; let balance = v.investments, months = 0; while (balance < target && months < 1200) { balance = balance * (1 + r) + v.monthlySavings; months++; } return [row("fireTarget", "FIRE target", money(target)), row("estimatedTime", "Estimated time", `${Math.floor(months / 12)}y ${months % 12}m`), row("gap", "Gap", money(Math.max(0, target - v.investments)))]; } },
  payoffinvest: { fields: [field("loanBalance", "Loan balance", 100000), field("loanRate", "Loan rate %", 5), field("extraMonthly", "Extra / month", 1000), field("investmentReturn", "Investment return %", 7)], calculate: v => [row("interestAvoided", "Interest avoided / year", money(v.loanBalance * v.loanRate / 100)), row("expectedReturn", "Expected investment return / year", money(v.extraMonthly * 12 * v.investmentReturn / 100)), row("higherRate", "Higher assumed rate", v.loanRate > v.investmentReturn ? "Pay off debt" : "Invest")] },
  runway: { fields: [field("cash", "Cash balance", 500000), field("monthlyRevenue", "Monthly revenue", 50000), field("monthlyExpenses", "Monthly expenses", 80000), field("monthlyGrowth", "Monthly growth %", 3)], calculate: v => { let cash = v.cash, revenue = v.monthlyRevenue, months = 0; while (cash > 0 && months < 240) { cash += revenue - v.monthlyExpenses; revenue *= 1 + v.monthlyGrowth / 100; months++; } return [row("monthlyBurn", "Current monthly burn", money(v.monthlyExpenses - v.monthlyRevenue)), row("runway", "Runway", cash > 0 ? "20+ years" : `${months} months`), row("annualRevenue", "Annualized revenue", money(v.monthlyRevenue * 12))]; } },
  profit: { fields: [field("salePrice", "Sale price", 100), field("productCost", "Product cost", 35), field("fees", "Fees %", 8), field("adCost", "Ad cost / order", 20)], calculate: v => { const profit = v.salePrice - v.productCost - v.salePrice * v.fees / 100 - v.adCost; return [row("profitOrder", "Profit / order", money(profit)), row("margin", "Margin", percent(profit / v.salePrice * 100)), row("hundredOrders", "100 orders", money(profit * 100))]; } },
  roas: { fields: [field("salePrice", "Sale price", 100), field("productCost", "Product cost", 35), field("fees", "Fees %", 8), field("variableCost", "Other variable cost", 7)], calculate: v => { const margin = v.salePrice - v.productCost - v.salePrice * v.fees / 100 - v.variableCost; return [row("contributionMargin", "Contribution margin", money(margin)), row("breakEvenSpend", "Break-even ad spend", money(margin)), row("breakEvenRoas", "Break-even ROAS", margin > 0 ? `${(v.salePrice / margin).toFixed(2)}×` : "Not viable")]; } },
  percentage: { fields: [field("oldValue", "Original value", 80), field("newValue", "New value", 100)], calculate: v => { const change = v.newValue - v.oldValue; return [row("absoluteChange", "Absolute change", number(change)), row("percentageChange", "Percentage change", v.oldValue ? percent(change / Math.abs(v.oldValue) * 100) : "Undefined"), row("direction", "Direction", change > 0 ? "Increase" : change < 0 ? "Decrease" : "No change")]; } },
  cagr: { fields: [field("startingValue", "Starting value", 10000), field("endingValue", "Ending value", 18000), field("years", "Years", 5)], calculate: v => { const rate = v.startingValue > 0 && v.endingValue >= 0 && v.years > 0 ? ((v.endingValue / v.startingValue) ** (1 / v.years) - 1) * 100 : NaN; return [row("cagr", "CAGR", Number.isFinite(rate) ? percent(rate) : "Invalid inputs"), row("totalGrowth", "Total growth", v.startingValue ? percent((v.endingValue / v.startingValue - 1) * 100) : "Undefined")]; } },
  marginmarkup: { fields: [field("cost", "Cost", 60), field("salePrice", "Sale price", 100)], calculate: v => { const profit = v.salePrice - v.cost; return [row("grossProfit", "Gross profit", money(profit)), row("grossMargin", "Gross margin", v.salePrice ? percent(profit / v.salePrice * 100) : "Undefined"), row("markup", "Markup", v.cost ? percent(profit / v.cost * 100) : "Undefined")]; } },
  tax: { fields: [field("price", "Price", 100), field("taxRate", "Tax rate %", 20)], calculate: v => { const added = v.price * v.taxRate / 100, included = v.price - v.price / (1 + v.taxRate / 100); return [row("priceWithTax", "Price with tax", money(v.price + added)), row("taxToAdd", "Tax to add", money(added)), row("taxIncluded", "Tax included in price", money(included)), row("priceBeforeTax", "Price before included tax", money(v.price - included))]; } },
  freelance: { fields: [field("incomeGoal", "Annual income goal", 100000), field("annualExpenses", "Annual business expenses", 15000), field("billableHours", "Billable hours / year", 1200), field("feePercent", "Platform and payment fees %", 10)], calculate: v => { const netHourly = (v.incomeGoal + v.annualExpenses) / Math.max(1, v.billableHours), posted = netHourly / Math.max(.01, 1 - v.feePercent / 100); return [row("minimumHourly", "Minimum hourly rate", money(netHourly)), row("postedHourly", "Rate including fees", money(posted)), row("dayRate", "Eight-hour day rate", money(posted * 8)), row("monthlyTarget", "Monthly revenue target", money((v.incomeGoal + v.annualExpenses) / 12))]; } },
};

export const getCalculator = (kind: string) => calculators[kind];
export const initialCalculatorValues = (definition: CalculatorDefinition) => Object.fromEntries(definition.fields.map(item => [item.key, item.defaultValue]));
