export const locales = ["en", "zh", "es", "hi", "ar"] as const;
export type Locale = (typeof locales)[number];

type Copy = {
  name: string; tagline: string; browse: string; search: string; all: string;
  developer: string; finance: string; privacy: string; open: string; input: string;
  output: string; copy: string; copied: string; clear: string; download: string;
  toolCount: string; local: string; noUpload: string; language: string;
  intro: string; popular: string; how: string; about: string; privacyTitle: string;
  privacyBody: string; noResult: string; calculations: string; reset: string;
  run: string; result: string; share: string; examples: string; note: string;
};

export const copy: Record<Locale, Copy> = {
  en: { name: "Integ Tools", tagline: "Private browser utilities", browse: "Browse tools", search: "Search tools", all: "All tools", developer: "Developer", finance: "Calculators", privacy: "Private by design", open: "Open tool", input: "Input", output: "Output", copy: "Copy", copied: "Copied", clear: "Clear", download: "Download", toolCount: "useful tools", local: "Runs locally", noUpload: "Nothing is uploaded", language: "Language", intro: "Fast, focused tools for data, code and better decisions.", popular: "Start with a useful tool", how: "How it works", about: "About this tool", privacyTitle: "Your data stays with you", privacyBody: "Every tool runs in your browser. We do not send pasted JSON, tokens, files or financial inputs to a server.", noResult: "No tools match that search.", calculations: "Practical calculators", reset: "Reset", run: "Run", result: "Result", share: "Copy link", examples: "Try an example", note: "Educational estimate — not financial advice." },
  zh: { name: "Integ 工具", tagline: "隐私优先的浏览器工具", browse: "浏览工具", search: "搜索工具", all: "全部工具", developer: "开发者", finance: "计算器", privacy: "隐私优先", open: "打开工具", input: "输入", output: "输出", copy: "复制", copied: "已复制", clear: "清空", download: "下载", toolCount: "实用工具", local: "本地运行", noUpload: "不会上传数据", language: "语言", intro: "为数据、代码和更好决策打造的快速专注工具。", popular: "从一个实用工具开始", how: "使用方式", about: "关于此工具", privacyTitle: "你的数据只属于你", privacyBody: "每个工具都在浏览器中运行。我们不会向服务器发送粘贴的 JSON、令牌、文件或财务输入。", noResult: "没有匹配的工具。", calculations: "实用计算器", reset: "重置", run: "运行", result: "结果", share: "复制链接", examples: "试用示例", note: "仅作教育性估算，并非财务建议。" },
  es: { name: "Integ Tools", tagline: "Utilidades privadas del navegador", browse: "Ver herramientas", search: "Buscar herramientas", all: "Todas", developer: "Desarrollo", finance: "Calculadoras", privacy: "Privacidad", open: "Abrir", input: "Entrada", output: "Salida", copy: "Copiar", copied: "Copiado", clear: "Limpiar", download: "Descargar", toolCount: "herramientas útiles", local: "Se ejecuta localmente", noUpload: "Sin subidas", language: "Idioma", intro: "Herramientas rápidas y precisas para datos, código y decisiones.", popular: "Empieza con una herramienta", how: "Cómo funciona", about: "Sobre esta herramienta", privacyTitle: "Tus datos se quedan contigo", privacyBody: "Todo se ejecuta en tu navegador. No enviamos JSON, tokens, archivos ni datos financieros a un servidor.", noResult: "No hay herramientas que coincidan.", calculations: "Calculadoras prácticas", reset: "Restablecer", run: "Ejecutar", result: "Resultado", share: "Copiar enlace", examples: "Probar ejemplo", note: "Estimación educativa; no es asesoramiento financiero." },
  hi: { name: "Integ Tools", tagline: "निजी ब्राउज़र यूटिलिटीज़", browse: "टूल देखें", search: "टूल खोजें", all: "सभी टूल", developer: "डेवलपर", finance: "कैलकुलेटर", privacy: "निजता पहले", open: "टूल खोलें", input: "इनपुट", output: "आउटपुट", copy: "कॉपी", copied: "कॉपी हुआ", clear: "साफ़ करें", download: "डाउनलोड", toolCount: "उपयोगी टूल", local: "लोकल चलता है", noUpload: "कुछ अपलोड नहीं होता", language: "भाषा", intro: "डेटा, कोड और बेहतर फैसलों के लिए तेज़ और स्पष्ट टूल।", popular: "किसी उपयोगी टूल से शुरू करें", how: "यह कैसे काम करता है", about: "इस टूल के बारे में", privacyTitle: "आपका डेटा आपके पास रहता है", privacyBody: "हर टूल आपके ब्राउज़र में चलता है। JSON, टोकन, फ़ाइल या वित्तीय इनपुट सर्वर को नहीं भेजे जाते।", noResult: "कोई मिलान टूल नहीं मिला।", calculations: "उपयोगी कैलकुलेटर", reset: "रीसेट", run: "चलाएँ", result: "नतीजा", share: "लिंक कॉपी", examples: "उदाहरण आज़माएँ", note: "केवल शैक्षिक अनुमान; वित्तीय सलाह नहीं।" },
  ar: { name: "أدوات Integ", tagline: "أدوات متصفح خاصة", browse: "تصفح الأدوات", search: "ابحث عن أداة", all: "كل الأدوات", developer: "للمطورين", finance: "الحاسبات", privacy: "الخصوصية أولاً", open: "فتح الأداة", input: "الإدخال", output: "الإخراج", copy: "نسخ", copied: "تم النسخ", clear: "مسح", download: "تنزيل", toolCount: "أداة مفيدة", local: "تعمل محليًا", noUpload: "دون رفع البيانات", language: "اللغة", intro: "أدوات سريعة ومركزة للبيانات والبرمجة والقرارات الأفضل.", popular: "ابدأ بأداة مفيدة", how: "كيف تعمل", about: "عن هذه الأداة", privacyTitle: "بياناتك تبقى معك", privacyBody: "تعمل كل أداة في متصفحك. لا نرسل JSON أو الرموز أو الملفات أو مدخلاتك المالية إلى خادم.", noResult: "لا توجد أدوات مطابقة.", calculations: "حاسبات عملية", reset: "إعادة ضبط", run: "تشغيل", result: "النتيجة", share: "نسخ الرابط", examples: "جرّب مثالاً", note: "تقدير تعليمي فقط، وليس نصيحة مالية." },
};

export const localizedToolNames: Record<Locale, Record<string, string>> = {
  en: {},
  zh: { "json-formatter": "JSON 格式化与校验", "base64": "Base64 编码与解码", "url-encoder": "URL 编码与解码", "jwt-inspector": "JWT 检查器", "regex-tester": "正则表达式测试", "timestamp": "时间戳转换", "uuid": "UUID 生成器", "hash": "SHA-256 哈希", "text-diff": "文本差异对比", "json-yaml": "JSON 转 YAML", "mortgage-leverage": "房贷杠杆计算器", "mortgage-prepayment": "提前还贷计算器", "rent-vs-buy": "租房还是买房", "compound-interest": "复利计算器", "fire": "FIRE 退休计算器", "saas-runway": "SaaS 资金跑道", "break-even-roas": "盈亏平衡 ROAS" },
  es: { "json-formatter": "Formateador JSON", "base64": "Codificador Base64", "url-encoder": "Codificador URL", "jwt-inspector": "Inspector JWT", "regex-tester": "Probador Regex", "timestamp": "Convertidor de fecha", "uuid": "Generador UUID", "hash": "Hash SHA-256", "text-diff": "Comparador de texto", "json-yaml": "JSON a YAML", "mortgage-leverage": "Apalancamiento hipotecario", "mortgage-prepayment": "Prepago hipotecario", "rent-vs-buy": "Alquilar o comprar", "compound-interest": "Interés compuesto", "fire": "Calculadora FIRE", "saas-runway": "Runway SaaS", "break-even-roas": "ROAS de equilibrio" },
  hi: { "json-formatter": "JSON फॉर्मैटर", "base64": "Base64 एन्कोडर", "url-encoder": "URL एन्कोडर", "jwt-inspector": "JWT इंस्पेक्टर", "regex-tester": "Regex टेस्टर", "timestamp": "टाइमस्टैम्प कन्वर्टर", "uuid": "UUID जनरेटर", "hash": "SHA-256 हैश", "text-diff": "टेक्स्ट डिफ", "json-yaml": "JSON से YAML", "mortgage-leverage": "मॉर्टगेज लीवरेज", "mortgage-prepayment": "मॉर्टगेज प्रीपेमेंट", "rent-vs-buy": "किराया या खरीद", "compound-interest": "चक्रवृद्धि ब्याज", "fire": "FIRE कैलकुलेटर", "saas-runway": "SaaS रनवे", "break-even-roas": "ब्रेक-ईवन ROAS" },
  ar: { "json-formatter": "تنسيق JSON", "base64": "ترميز Base64", "url-encoder": "ترميز URL", "jwt-inspector": "فاحص JWT", "regex-tester": "اختبار Regex", "timestamp": "محول الطابع الزمني", "uuid": "مولد UUID", "hash": "تجزئة SHA-256", "text-diff": "مقارنة النص", "json-yaml": "JSON إلى YAML", "mortgage-leverage": "رافعة الرهن العقاري", "mortgage-prepayment": "السداد المبكر للرهن", "rent-vs-buy": "استئجار أم شراء", "compound-interest": "الفائدة المركبة", "fire": "حاسبة FIRE", "saas-runway": "مدة SaaS النقدية", "break-even-roas": "ROAS نقطة التعادل" },
};
