export type Category = "developer" | "finance";
export type Tool = { slug: string; name: string; description: string; category: Category; kind: string; keywords: string[]; about: string; how: string };
const dev = (slug: string, name: string, description: string, kind: string, keywords: string[] = []) => ({ slug, name, description, category: "developer" as const, kind, keywords, about: description + " Processing happens only in this browser.", how: "Paste or enter your data, choose an action, then copy or download the local result." });
const fin = (slug: string, name: string, description: string, kind: string, keywords: string[] = []) => ({ slug, name, description, category: "finance" as const, kind, keywords, about: description + " Change the assumptions to explore your own scenario.", how: "Enter your assumptions and review the calculated estimate and breakdown." });

export const tools: Tool[] = [
  { slug: 'component-scanner', name: 'Resistor & Inductor Camera Reader', description: 'Scan color bands with your phone camera to read nominal resistance or inductance locally. Experimental; verify the detected colors.', category: 'developer', kind: 'component-scanner', keywords: ['resistor', 'inductor', 'color code', 'camera', '电阻', '电感', '色环', '阻值'], about: 'Read common 4/5-band resistors, 4-band EIA inductors and 5-band MIL inductors. Select the component type, review camera candidates and correct colors locally. This reads marked nominal values rather than measuring the component.', how: 'Allow rear-camera access. Hold a single component roughly horizontally near the middle; the detector follows its body and magnifies it. Keep every band visible under diffuse light, wait for consistent frames, then pause to check or correct colors.' },
  dev("json-formatter", "JSON Formatter & Validator", "Format, validate, minify and inspect JSON instantly.", "json", ["beautifier", "tree"]),
  dev("json-yaml", "JSON to YAML Converter", "Convert JSON objects and arrays to readable YAML locally.", "yaml", ["json to yaml", "yaml converter"]),
  dev("json-csv", "JSON to CSV Converter", "Convert arrays of JSON objects to properly quoted CSV rows.", "csv", ["json to csv", "csv export"]),
  dev("base64", "Unicode Base64 Encoder & Decoder", "Encode or decode UTF-8 and Unicode text with Base64.", "base64", ["base64 encode", "base64 decode", "utf8"]),
  dev("url-encoder", "URL Encode, Decode & Parser", "Encode URLs and inspect query parameters.", "url", ["query", "percent"]),
  dev("html-entities", "HTML Entity Encode & Decode", "Escape HTML safely or decode common entities.", "html", ["escape", "html"]),
  dev("unicode-escape", "Unicode Escape Converter", "Escape Unicode characters for JSON and JavaScript.", "unicode", ["unicode", "escape"]),
  dev("jwt-inspector", "JWT Inspector", "Decode JWT headers and claims locally, with expiry details.", "jwt", ["token", "oauth"]),
  dev("hash-hmac", "SHA-256, SHA-512 & HMAC", "Create browser-native cryptographic hashes and HMAC-SHA256.", "hash", ["sha256", "sha512", "hmac"]),
  dev("uuid", "UUID v4 Generator", "Generate secure UUID v4 values locally.", "uuid", ["guid", "random"]),
  dev("password-generator", "Random Secret & Password", "Generate high-entropy passwords and secrets.", "password", ["secret", "random"]),
  dev("regex-tester", "Regex Tester", "Test JavaScript regular expressions with live matches.", "regex", ["regular expression", "replace"]),
  dev("text-diff", "Text Diff", "Compare two text blocks line by line.", "diff", ["compare"]),
  dev("case-converter", "Case Converter", "Convert text to camelCase, snake_case, kebab-case and more.", "case", ["camel", "snake", "slug"]),
  dev("sort-dedupe-lines", "Sort & Deduplicate Lines", "Sort lines and remove duplicates while preserving local privacy.", "lines", ["sort", "unique"]),
  dev("timestamp", "Unix Timestamp Converter", "Convert Unix seconds, milliseconds and ISO 8601 dates.", "timestamp", ["date", "epoch"]),
  dev("timezone-converter", "Timezone Converter", "View a date and time in major world time zones.", "timezone", ["date", "time"]),
  dev("cron-explainer", "Cron Explainer", "Explain common cron expressions and show upcoming runs.", "cron", ["schedule"]),
  dev("chmod-calculator", "Chmod Calculator", "Translate Unix permission numbers into rwx permissions.", "chmod", ["permission", "unix"]),
  dev("color-contrast", "Color Converter & Contrast", "Convert HEX colors and check WCAG contrast.", "color", ["wcag", "rgb"]),
  dev("px-rem", "PX / REM Converter", "Convert pixels and rems using your root font size.", "pxrem", ["css", "rem"]),
  dev("curl-to-fetch", "cURL to Fetch", "Turn a common cURL request into browser Fetch code.", "curl", ["api", "fetch"]),
  dev("http-header-parser", "HTTP Header Parser", "Parse raw HTTP headers into structured values.", "headers", ["http", "api"]),
  dev("data-uri", "Data URI Generator", "Create or inspect data: URIs for small assets.", "datauri", ["base64", "image"]),
  dev("qr-code-generator", "QR Code Generator", "Create customizable QR codes for links and text, then download PNG or SVG files.", "qrcode", ["qr code", "barcode", "二维码", "png", "svg"]),
  dev("slug-generator", "Slug Generator", "Create clean URL slugs from any text.", "slug", ["url", "seo"]),
  dev("word-counter", "Word Counter", "Count words, characters, lines and reading time.", "wordcount", ["text"]),
  dev("json-to-typescript", "JSON to TypeScript", "Generate TypeScript interfaces from JSON objects and API responses.", "json-typescript", ["json", "typescript", "interface", "api"]),
  dev("jsonpath-tester", "JSONPath Tester", "Read nested JSON values with familiar dot and bracket paths.", "jsonpath", ["json path", "query", "nested json"]),
  dev("jsonl-validator", "JSONL Validator", "Validate newline-delimited JSON and report the exact failing row.", "jsonl", ["ndjson", "json lines", "fine tuning"]),
  dev("sql-formatter", "SQL Formatter", "Format common SQL queries for easier review and debugging.", "sql", ["sql beautifier", "query formatter"]),
  dev("xml-formatter", "XML Formatter", "Beautify or minify XML and detect malformed markup.", "xml", ["xml beautifier", "minify"]),
  dev("query-string-parser", "Query String Parser", "Parse, edit and inspect URL query parameters, including repeated keys.", "querystring", ["url params", "utm", "query parameters"]),
  dev("number-base-converter", "Binary, Decimal & Hex Converter", "Convert integers between binary, octal, decimal and hexadecimal.", "numberbase", ["hex to decimal", "binary converter", "octal"]),
  dev("binary-text-converter", "Binary to Text Converter", "Convert UTF-8 text to binary bytes and binary back to text.", "binarytext", ["binary translator", "ascii", "utf8"]),
  dev("base32-encoder", "Base32 Encoder & Decoder", "Encode or decode RFC 4648 Base32 text locally.", "base32", ["totp", "base32 decode", "rfc4648"]),
  dev("lorem-ipsum-generator", "Lorem Ipsum Generator", "Generate useful placeholder paragraphs for layouts and prototypes.", "lorem", ["placeholder text", "dummy text"]),
  dev("markdown-preview", "Markdown Preview & HTML", "Convert common Markdown syntax to safe preview-ready HTML.", "markdown", ["markdown editor", "md to html"]),
  dev("user-agent-parser", "User-Agent Parser", "Identify common browsers, operating systems and device types from a user-agent string.", "useragent", ["browser detector", "device parser"]),
  dev("http-status-codes", "HTTP Status Code Lookup", "Look up common HTTP response codes, meanings and categories.", "httpstatus", ["404", "500", "http code"]),
  dev("mime-type-lookup", "MIME Type Lookup", "Find common content types by file extension or MIME type.", "mime", ["content type", "file extension"]),
  dev("subnet-calculator", "IPv4 Subnet Calculator", "Calculate network, broadcast, host range and address count from CIDR.", "subnet", ["cidr", "ip calculator", "network"]),
  dev("download-time-calculator", "Download Time Calculator", "Estimate transfer time from file size and connection speed.", "downloadtime", ["file transfer", "mbps", "bandwidth"]),
  dev("token-estimator", "LLM Token Estimator", "Estimate token count and context usage for prompts without uploading text.", "tokens", ["chatgpt tokens", "context window", "prompt"]),
  dev("pii-redactor", "PII & Secret Redactor", "Mask emails, phone numbers, IP addresses, API keys and JWTs before sharing text.", "redactor", ["privacy", "remove sensitive data", "prompt security"]),
  dev("codex-plan-cost", "Codex Plan Cost Comparator", "Compare Codex-enabled ChatGPT plans across countries, currencies, taxes and team sizes.", "codex-plan-cost", ["codex pricing", "chatgpt plan", "regional price", "subscription"]),
  dev("codex-reset-timer", "Codex Usage Reset Timer", "Save the reset time shown by Codex and track the countdown locally.", "codex-reset", ["codex limit", "5 hour limit", "weekly reset", "usage tracker"]),
  dev("codex-credit-estimator", "Codex Credit Estimator", "Estimate Codex credits from input, cached input and output tokens using the current rate card.", "codex-credits", ["codex credits", "token cost", "usage estimate", "gpt-5.5"]),
  fin("mortgage-payment", "Mortgage Payment & Amortization", "Calculate fixed-rate monthly payments, total interest and amortization.", "mortgage", ["loan", "amortization"]),
  fin("mortgage-leverage", "Mortgage Leverage & Downside", "Model property equity, leverage and price-drop downside scenarios.", "leverage", ["property", "loan"]),
  fin("mortgage-prepayment", "Mortgage Prepayment Calculator", "Estimate the interest and time saved by paying extra.", "prepayment", ["loan", "interest"]),
  fin("rent-vs-buy", "Rent vs Buy Calculator", "Compare estimated housing costs over a chosen horizon.", "rentbuy", ["home", "property"]),
  fin("rental-property-return", "Rental Property Return", "Estimate rental yield, annual cash flow and cap rate.", "rental", ["yield", "property"]),
  fin("compound-interest", "Compound Interest Calculator", "Project savings with monthly contributions and compounding.", "compound", ["invest", "savings"]),
  fin("fire", "FIRE Calculator", "Estimate a financial independence target and timeline.", "fire", ["retirement"]),
  fin("loan-payoff-vs-invest", "Loan Payoff vs Invest", "Compare reducing debt with investing a monthly extra amount.", "payoffinvest", ["loan", "invest"]),
  fin("saas-runway", "SaaS Runway Calculator", "Estimate cash runway from cash, revenue and expenses.", "runway", ["burn", "cash"]),
  fin("product-profit", "Product Profit Calculator", "Calculate contribution profit, margin and break-even orders.", "profit", ["ecommerce", "margin"]),
  fin("break-even-roas", "Break-even ROAS Calculator", "Find the minimum ad return needed to avoid a loss.", "roas", ["ads", "ecommerce"]),
  fin("percentage-change", "Percentage Change Calculator", "Calculate percentage increase, decrease and absolute difference.", "percentage", ["percent increase", "percent decrease"]),
  fin("cagr", "CAGR Calculator", "Calculate compound annual growth rate from starting and ending values.", "cagr", ["annual growth rate", "investment return"]),
  fin("margin-markup", "Margin & Markup Calculator", "Convert between cost, sale price, gross margin and markup.", "marginmarkup", ["profit margin", "markup percentage", "pricing"]),
  fin("vat-sales-tax", "VAT & Sales Tax Calculator", "Add or remove VAT or sales tax from a price.", "tax", ["vat calculator", "sales tax", "gst"]),
  fin("freelance-rate", "Freelance Hourly Rate Calculator", "Turn income goals, expenses and billable capacity into a sustainable hourly rate.", "freelance", ["consulting rate", "hourly rate", "platform fee", "freelancer"]),
];
export const findTool = (slug?: string) => tools.find(tool => tool.slug === slug);
